use actix_web::dev::ServiceResponse;
use actix_web::middleware::{ErrorHandlerResponse, ErrorHandlers};
use actix_web::{dev, ResponseError, Result};

use crate::error::error_json::ErrorJson;
use crate::error::AppError;

#[inline]
fn is_generated_from<E, B>(res: &dev::ServiceResponse<B>) -> bool
where
    E: actix_web::error::ResponseError + 'static,
{
    res.response()
        .error()
        .and_then(|err| err.as_error::<E>())
        .is_some()
}

#[allow(clippy::unnecessary_wraps)]
fn to_json_error<B: 'static>(res: dev::ServiceResponse<B>) -> Result<ErrorHandlerResponse<B>> {
    // Sanity check, this should never happend because API endpoints should
    // always return `AppError` and never directly `ErrorJson`.
    //
    // And we don't even expose ErrorJson, so this really shouldn't happen.
    if is_generated_from::<ErrorJson, _>(&res) {
        err_trace!("to_json_error: it's a json error??!!? üò®");
    }

    // App error is already good to go.
    if is_generated_from::<AppError, _>(&res) {
        err_trace!("to_json_error: it's an app error, let it through üòè");
        // map_into_left_body means return the already generated response
        return Ok(ErrorHandlerResponse::Response(res.map_into_left_body()));
    };

    // `res` is either the error response generated
    // from a generic actix::Error or from an AppError (I guess).
    let (req, res) = res.into_parts();

    err_trace!("to_json_error: it's some other error, convert it! üòà");
    let err_json_response = ErrorJson::from_response(res).error_response();

    // map_into_right_body means return this newly generated response
    Ok(ErrorHandlerResponse::Response(
        ServiceResponse::new(req, err_json_response).map_into_right_body(),
    ))
}

pub(crate) fn error_handler<B: 'static>() -> ErrorHandlers<B> {
    ErrorHandlers::<B>::new().default_handler(to_json_error)
}
